In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Retail Data.csv")

In [3]:
df

,Order No,Order Date,Customer Name,Address,City,State,Customer Type,Account Manager,Order Priority,Product Name,...,Cost Price,Retail Price,Profit Margin,Order Quantity,Sub Total,Discount %,Discount $,Order Total,Shipping Cost,Total
0,4293-1,02-09-2014,Vivek Sundaresam,"152 Bunnerong Road,Eastgardens",Sydney,NSW,Small Business,Tina Carlton,Critical,UGen Ultra Professional Cordless Optical Suite,...,$156.50,$300.97,$144.47,23.0,"$4,533.52",2%,$194.83,"$4,757.22",$7.18,"$4,291.55"
1,5001-1,24-10-2015,Shahid Hopkins,"438 Victoria Avenue,Chatswood",Sydney,NSW,Corporate,Natasha Song,Medium,Bagged Rubber Bands,...,$0.24,$1.26,$1.02,8.0,$45.20,3%,$0.00,$45.90,$0.70,$46.91
2,5004-1,13-03-2014,Dennis Pardue,"412 Brunswick St,Fitzroy",Melbourne,VIC,Consumer,Connor Betts,Not Specified,TechSavi Cordless Navigator Duo,...,$42.11,$80.98,$38.87,45.0,$873.32,4%,$72.23,$837.57,$7.18,$82.58
3,5009-1,18-02-2013,Sean Wendt,"145 Ramsay St,Haberfield",Sydney,NSW,Small Business,Phoebe Gour,Critical,Artisan Printable Repositionable Plastic Tabs,...,$5.33,$8.60,$3.27,16.0,$73.52,1%,$4.35,$740.67,$6.19,$730.92
4,5010-1,13-09-2014,Christina Vanderzanden,"188 Pitt Street,Sydney",Sydney,NSW,Small Business,Tina Carlton,Not Specified,Pizazz Drawing Pencil Set,...,$1.53,$2.78,$1.25,49.0,$138.46,7%,$5.95,$123.77,$1.34,$125.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,6831-1,02-11-2016,Roland Murray,"438 Victoria Avenue,Chatswood",Sydney,NSW,Corporate,Natasha Song,Critical,Artisan Hi-Liter Smear-Safe Highlighters,...,$2.98,$5.84,$2.86,35.0,$115.40,2%,$10.81,$104.09,$0.83,$101.22
4996,6847-1,16-12-2015,Patrick OBrill,"63 Riley Street,Woolloomooloo",Sydney,NSW,Small Business,Tina Carlton,Not Specified,Smiths Colored Interoffice Envelopes,...,$19.83,$30.98,$11.15,49.0,"$1,999.69",7%,$143.91,"$1,947.75",$19.51,"$1,052.55"
4997,6922-1,28-09-2016,Troy Staebel,"1-2/299 Sussex St,Sydney",Sydney,NSW,Consumer,Aanya Zhang,Low,Laser DVD-RAM discs,...,$20.18,$35.41,$15.23,19.0,$929.40,9%,$27.88,$901.52,$1.99,$921.03
4998,6939-1,18-06-2016,Shaun Weien,"Shop 3/144 Wattle St,Ultimo",Sydney,NSW,Corporate,Samantha Chairs,Not Specified,Artisan 479 Labels,...,$1.59,$2.61,$1.02,23.0,$66.54,5%,$4.46,$63.77,$0.50,$64.27
4999,6980-1,12-08-2015,Nora Pelletier,"5/250 Old Northern Road,Castle Hill",Sydney,NSW,Consumer,Nicholas Fernandes,Low,Binder Posts,...,$3.50,$5.74,$2.24,31.0,$213.34,0%,$4.67,$216.51,$5.01,$221.52

1.	View the structure of the dataset (columns, types, missing values).
Ans. Columns = 24,

     data type:
     
        - mostly object(string)
        - order quentity -> numerice(float)
        - price columns stored as text ($, , present)

      Missing Values

         - Address → 1 missing
         - Order Quantity → 1 missing
         - Others → complete
         
      Insight
      
         - Dataset initially contains dirty financial data (currency symbols) and requires preprocessing before analysis.

In [ ]:
df.columns

Index(['Order No', 'Order Date', 'Customer Name', 'Address', 'City', 'State',
       'Customer Type', 'Account Manager', 'Order Priority', 'Product Name',
       'Product Category', 'Product Container', 'Ship Mode', 'Ship Date',
       'Cost Price', 'Retail Price', 'Profit Margin', 'Order Quantity',
       'Sub Total', 'Discount %', 'Discount $', 'Order Total', 'Shipping Cost',
       'Total'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order No           5000 non-null   object
 1   Order Date         5000 non-null   object
 2   Customer Name      5000 non-null   object
 3   Address            4999 non-null   object
 4   City               5000 non-null   object
 5   State              5000 non-null   object
 6   Customer Type      5000 non-null   object
 7   Account Manager    5000 non-null   object
 8   Order Priority     5000 non-null   object
 9   Product Name       5000 non-null   object
 10  Product Category   5000 non-null   object
 11  Product Container  5000 non-null   object
 12  Ship Mode          5000 non-null   object
 13  Ship Date          5000 non-null   object
 14  Cost Price         5000 non-null   object
 15  Retail Price       5000 non-null   object
 16  Profit Margin      5000 non-null   object
 17  Order Quantity     4999 non-null   float64
 18  Sub Total          5000 non-null   object
 19  Discount %         5000 non-null   object
 20  Discount $         5000 non-null   object
 21  Order Total        5000 non-null   object
 22  Shipping Cost      5000 non-null   object
 23  Total              5000 non-null   object
dtypes: float64(1), object(23)
memory usage: 937.6+ KB

In [ ]:
#checking is  the null value in data 
df.isnull().sum()

Order No             0
Order Date           0
Customer Name        0
Address              1
City                 0
State                0
Customer Type        0
Account Manager      0
Order Priority       0
Product Name         0
Product Category     0
Product Container    0
Ship Mode            0
Ship Date            0
Cost Price           0
Retail Price         0
Profit Margin        0
Order Quantity       1
Sub Total            0
Discount %           0
Discount $           0
Order Total          0
Shipping Cost        0
Total                0
dtype: int64

2.	What is the shape (rows, columns) of the dataset? 

Ans.
Rows = 5000
Columns = 24

In [ ]:
# Rows
df.shape[0]

5000

In [ ]:
#columns
df.shape[1]

24

3.	Are there any duplicate records?

Ans. Duplicates = 0, Data integrity is good — no duplicate transactions.

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [Order No, Order Date, Customer Name, Address, City, State, Customer Type, Account Manager, Order Priority, Product Name, Product Category, Product Container, Ship Mode, Ship Date, Cost Price, Retail Price, Profit Margin, Order Quantity, Sub Total, Discount %, Discount $, Order Total, Shipping Cost, Total]
Index: []

[0 rows x 24 columns]

4.	Are there any missing or corrupted entries in Ship Date, Order Date, or numeric columns?

Ans. ship date -> 0 missing
     order date -> 0 missing

     - no missing date

In [ ]:
df['Ship Date'].isnull().sum()

np.int64(0)

In [ ]:
df['Order Date'].isnull().sum()

np.int64(0)

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'],dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

df[['Order Date','Ship Date']].isnull().sum()

Order Date    0
Ship Date     0
dtype: int64

In [ ]:
numeric_cols = [
    'Order Quantity','Cost Price','Retail Price',
    'Profit Margin','Sub Total','Discount $',
    'Order Total','Shipping Cost','Total'
]
df[numeric_cols].isnull().sum()

Order Quantity    1
Cost Price        0
Retail Price      0
Profit Margin     0
Sub Total         0
Discount $        0
Order Total       0
Shipping Cost     0
Total             0
dtype: int64

In [ ]:
df = df.dropna(subset=['Order Quantity'])

5.	Convert Order Date and Ship Date to datetime.
Ans. successfully converted.

In [ ]:

df[['Order Date','Ship Date']].dtypes

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

6.  Check for future or inconsistent shipping dates. 

Ans. Ship Date < Order Date = 75 records 

Insight 

- Data quality issue — some shipments occur before orders.

In [ ]:
invalid_shipping = df[df['Ship Date'] < df['Order Date']]
invalid_shipping.shape

(75, 24)

In [ ]:
df = df[df['Ship Date'] >= df['Order Date']]

In [ ]:
df[df['Ship Date'] < df['Order Date']].shape

(0, 24)

In [ ]:
df[df['Ship Date'] >= df['Order Date']].shape

(4924, 24)

7.	Convert price columns to numeric (remove $ and commas).

In [ ]:
df.dtypes

Order No                     object
Order Date           datetime64[ns]
Customer Name                object
Address                      object
City                         object
State                        object
Customer Type                object
Account Manager              object
Order Priority               object
Product Name                 object
Product Category             object
Product Container            object
Ship Mode                    object
Ship Date            datetime64[ns]
Cost Price                   object
Retail Price                 object
Profit Margin                object
Order Quantity              float64
Sub Total                    object
Discount %                   object
Discount $                   object
Order Total                  object
Shipping Cost                object
Total                        object
dtype: object

In [ ]:
price_col = [
    'Cost Price',
    'Retail Price',
    'Profit Margin',
    'Sub Total',
    'Order Total',
    'Shipping Cost',
    'Total'
]

In [ ]:
for col in price_col:
    df.loc[:, col] = df[col].astype(str).str.replace('$','', regex=False)
    df.loc[:, col] = df[col].str.replace(',','', regex=False)
    df.loc[:, col] = df[col].astype(float)
    
df['Cost Price']

0       156.5
1        0.24
2       42.11
3        5.33
4        1.53
        ...
4995     2.98
4996    19.83
4997    20.18
4998     1.59
4999      3.5
Name: Cost Price, Length: 4924, dtype: object

8. What are the unique values in Customer Type and Order Priority?

Ans. 

- Customer Type

Small Business

Corporate

Consumer

Home Office

- Order Priority

Critical

High

Medium

Low

Not Specified

In [ ]:
df['Customer Type'].unique()

array(['Small Business', 'Corporate', 'Consumer', 'Home Office'],
      dtype=object)

In [ ]:

df['Order Priority'].unique()

array(['Critical', 'Medium', 'Not Specified', 'Low', 'High'], dtype=object)

9.	What are the most common shipping modes?

Ans. most common shipping modes - Regular Air  4176

In [ ]:
df['Ship Mode'].value_counts()

Ship Mode
Regular Air       4176
Express Air        632
Delivery Truck     116
Name: count, dtype: int64

10.	Which cities have the highest number of orders?

Ans. Sydney  3528,
     Melbourne    1396

In [ ]:
df['City'].value_counts().head(10)

City
Sydney       3528
Melbourne    1396
Name: count, dtype: int64

11.	What’s the range of order quantities and prices? 

Ans.  order quantities - range 1 to 50
    
      price - range 1.14 to 599.99

In [ ]:
df['Order Quantity'].min(), df['Order Quantity'].max()

(np.float64(1.0), np.float64(50.0))

In [ ]:

df['Retail Price'].min(), df['Retail Price'].max()

(1.14, 599.99)

12.	Create a new column for shipping duration.

In [ ]:
df['Shipping Duration'] = (
    df['Ship Date'] - df['Order Date']
).dt.days

df['Shipping Duration'].describe()

count    4924.000000
mean        2.688465
std        14.059796
min         0.000000
25%         1.000000
50%         2.000000
75%         2.000000
max       370.000000
Name: Shipping Duration, dtype: float64

13.	Are there any orders with zero or negative total or quantity? 

Ans.

In [ ]:
df[(df['Order Quantity'] <= 0) | (df['Total'] <= 0 ) ]

Empty DataFrame
Columns: [Order No, Order Date, Customer Name, Address, City, State, Customer Type, Account Manager, Order Priority, Product Name, Product Category, Product Container, Ship Mode, Ship Date, Cost Price, Retail Price, Profit Margin, Order Quantity, Sub Total, Discount %, Discount $, Order Total, Shipping Cost, Total, Shipping Duration]
Index: []

[0 rows x 25 columns]

14.	Are all discount percentages matching discount dollar amounts?

Ans.

In [ ]:
df['Sub Total'].dtype
df['Discount %'].info()

<class 'pandas.core.series.Series'>
Index: 4924 entries, 0 to 4999
Series name: Discount %
Non-Null Count  Dtype
--------------  -----
4924 non-null   object
dtypes: object(1)
memory usage: 76.9+ KB

In [ ]:
df['Discount %'] = df['Discount %'].str.replace('%','', regex=False).astype(float)

In [ ]:
df['Sub Total'] = pd.to_numeric(df['Sub Total'])
df['Discount %'] = pd.to_numeric(df['Discount %'])
df['Expected Discount'] = df['Sub Total'] * df['Discount %'] / 100

In [ ]:
df['Discount %']

0       2.0
1       3.0
2       4.0
3       1.0
4       7.0
       ...
4995    2.0
4996    7.0
4997    9.0
4998    5.0
4999    0.0
Name: Discount %, Length: 4924, dtype: float64

In [ ]:
df['Expected Discount']

0        90.6704
1         1.3560
2        34.9328
3         0.7352
4         9.6922
          ...
4995      2.3080
4996    139.9783
4997     83.6460
4998      3.3270
4999      0.0000
Name: Expected Discount, Length: 4924, dtype: float64

In [ ]:
df['Discount $'].dtype

dtype('O')

In [ ]:
df['Expected Discount'] = df['Expected Discount'].astype(float)

df['Discount $'] = df['Discount $'].str.replace('$','', regex=False)\
                                   .str.replace(',','', regex=False)\
                                   .astype(float)

discount_mismatch = df[
    abs(df['Expected Discount'] - df['Discount $']) > 1
]

discount_mismatch.shape

(3916, 26)

In [ ]:
discount_mismatch[['Retail Price','Sub Total','Discount %','Discount $','Expected Discount']].head()

  Retail Price  Sub Total  Discount %  Discount $  Expected Discount
0       300.97    4533.52         2.0      194.83            90.6704
1         1.26      45.20         3.0        0.00             1.3560
2        80.98     873.32         4.0       72.23            34.9328
3          8.6      73.52         1.0        4.35             0.7352
4         2.78     138.46         7.0        5.95             9.6922

-Insight
  
    Discount % does Not match Discount $ in most rows -> calculation inconsistency

16.	Identify top 5 products by order quantity.

In [4]:
top = df.groupby("Product Name")["Order Quantity"].sum().sort_values(ascending=False).head(5)
top

Product Name
Artisan 474 Labels                         3395.0
Smiths General Use 3-Ring Binders          3220.0
Artisan 479 Labels                         3039.0
Artisan 481 Labels                         2996.0
Apex Preferred Stainless Steel Scissors    2896.0
Name: Order Quantity, dtype: float64

18.	What is the average shipping cost by mode?

In [6]:
average = df.groupby("Ship Mode")["Shipping Cost"].mean()
average

TypeError: agg function failed [how->mean,dtype->object]

19.	Find the most profitable product.

In [7]:
profit = df.groupby("Product Name")["Profit Margin"].sum().sort_values(ascending=False)
profit

Product Name
Economy Rollaway Files                                                         $97.47$97.47$97.47$97.47$97.47$97.47$97.47$97....
300 Series Non-Flip                                                            $93.59$93.59$93.59$93.59$93.59$93.59$93.59$93....
3Max Polarizing Task Lamp with Clamp Arm, Light Gray                           $80.82$80.82$80.82$80.82$80.82$80.82$80.82$80....
Artisan Hi-Liter GlideStik Fluorescent Task Lamp with Clamp Arm, Light Gray                                               $80.82
PastelOcean Color Pencil Set                                                   $8.73$8.73$8.73$8.73$8.73$8.73$8.73$8.73$8.73$...
                                                                                                     ...
Sciths General Use 3-Ring Binders                                                                                          $0.70
Steady Pocket Accent Highlighters                                              $0.67$0.67$0.67$0.67$0.67$0.67$0.67$0.67$0.67$...
Pizazz Dustless Chalk Sticks                                                   $0.59$0.59$0.59$0.59$0.59$0.59$0.59$0.59$0.59$...
Binder Clips by OIC                                                            $0.55$0.55$0.55$0.55$0.55$0.55$0.55$0.55$0.55$...
OIC Thumb-Tacks                                                                $0.43$0.43$0.43$0.43$0.43$0.43$0.43$0.43$0.43$...
Name: Profit Margin, Length: 257, dtype: object

In [8]:
''' Which Account Manager handled the most revenue? '''
account = retail.groupby("Account Manager")["Total"].sum().sort_values(ascending=False)
account

NameError: name 'retail' is not defined

In [ ]:
''' Create a new column for shipping duration.'''
df["Shipping Duration"] = df["Ship Date"] - df["Order Date"]
df

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
''' Create a new column for shipping duration.'''
inconsistentdate = df["Ship Date"] < df["Order Date"]
print(inconsistentdate)

In [ ]:
'''Are there any orders with zero or negative total or quantity?'''
order = df[(df["Total"]<=0) | (df["Order Quantity"]<=0)]
order

In [ ]:
'''What is the total revenue generated across all orders?'''
total_revenue = df["Total"].sum()
total_revenue

In [ ]:
'''Which customer type generates more revenue?'''
customer_type = df.groupby("Customer Type")["Total"].sum().sort_values(ascending=False)
customer_type

In [ ]:
''' How does order priority affect revenue? '''
order_priority_revenue = df.groupby("Order Priority")["Total"].sum().sort_values(ascending=False)
order_priority_revenue

In [ ]:
'''What is the average profit margin by product category? '''
average_profit = df.groupby("Product Category")["Profit Margin"].mean()
average_profit

In [ ]:
'''What is the most profitable product overall? '''
profitable_product = df.groupby("Product Name")["Total"].sum().sort_values(ascending=False)
profitable_product

In [ ]:
'''How many days does it usually take to ship an order? '''
ship_days = df["Shipping Duration"].mean()
ship_days

In [ ]:
'''Do longer shipping times impact profit margins?'''
profit_shipping = df["Shipping Duration"].corr(df["Profit Margin"])
profit_shipping

In [ ]:
'''Which city brings in the highest revenue? '''
city_revenue = df.groupby("City")["Total"].sum().sort_values(ascending=False)
city_revenue

In [ ]:
'''Which account manager generated the most revenue? '''
manager = df.groupby("Account Manager")["Total"].sum().sort_values(ascending=False).reset_index().head(5)
manager

In [ ]:
'''Which shipping mode is most cost-effective (lowest avg. shipping)?'''
ship_cost_effective = df.groupby("Ship Mode")["Shipping Cost"].mean().sort_values()
ship_cost_effective

In [ ]:
'''Do higher discounts reduce profits?'''
df["Discount %"] = df["Discount %"].str.replace('%','')
df["Discount %"] = pd.to_numeric(df["Discount %"])

In [ ]:
'''Do higher discounts reduce profits?'''
discount = df["Discount %"].corr(df["Profit Margin"])
discount

In [ ]:
'''Which state has the highest number of orders?'''
state = df.groupby("State")["Order Quantity"].sum()
state

In [ ]:
'''What is the average discount % across all orders?'''
average_discount = df.groupby("Order Total")["Discount %"].mean().reset_index().head(5)
average_discount

In [ ]:
'''Are certain containers (e.g., Small Box, Wrap Bag) more profitable?'''
container = df.groupby("Product Container")["Profit Margin"].sum().sort_values(ascending=False).reset_index()
container

From the above analysis, we got to know that:-
1) Corporate customer type generates more revenue of 1373796.44.
2) Average Profit Margin of Technology is higher 20.423208 as compared to furniture and office supplies.
3) Cando PC940 Copier generates profit of 695199.82 which makes it profitable product as comapred to other products.
4) As shipping duration increases profit margin decreases.
5) Sydney generates more revenue 2678780.33 as comapred to Melbourne 1052756.07.
6) Connor Betts manager has managed more order as he has generated more revenue of 671173.17.
7) Express Air is cost effective mode of shipping its average charge is 5.247311.
8) As discount increases it affects the profit margin and profit slightly decreases.
9) small box and wrap bags are more profitable.